---
version: '3.8'
services:
  pysimple:
    build:
      context: '.'
    image: alanbchristie/pysimple:latest
    container_name: pysimple
    ports:
    - '8080:8080'
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
    - '6379:6379'
